import React from "react";
import type { Metadata } from "next";
import "../styles/globals.css";
import { Footer, Header } from "shared/ui";
import StoreProvider from "./store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-secondary-default h-screen`}>
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
