import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import { Footer, Header } from "components";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-secondary-default h-screen`}>
        <Header />
        {children}
        <Footer  />
      </body>
    </html>
  );
}
