name: Continuous Integration

on:
    push:
        branches:
            - master

env:
    base-url: http://localhost:3000

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            -name: Checkout Typescript errors
              run: npm run i -g typescript && tsc

            - name: Checkout ESLint errors
              run: npm run eslint

            - name: Launch unit tests
              run: npm run test

            - name: Save build
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: .next
